name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Prettify
        run: bun run prettify

      - name: Build project
        run: bun run build

      - name: Git Status
        run: git status

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            echo "Committing changes..."
            git commit -m "build"
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            git fetch origin $BRANCH_NAME
            git rebase --strategy-option=theirs origin/$BRANCH_NAME
            git push origin HEAD:$BRANCH_NAME
          else
            echo "No changes to commit."
          fi
