name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prettify
        run: npm run prettify

      - name: Build project
        run: npm run build

      - name: Git Status
        run: git status

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            echo "Committing changes..."
            git commit -m "build"
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            git fetch origin $BRANCH_NAME
            git rebase --strategy-option=theirs origin/$BRANCH_NAME
            git push origin HEAD:$BRANCH_NAME
          else
            echo "No changes to commit."
          fi
